spring:
  application:
    name: fit-nexus
  jpa:
    hibernate:
      ddl-auto: update #none, update...

#To connect directly to postgresql DB up and running in local machine
#    datasource:
#      name: fitnexusdb
#      url: jdbc:postgresql://localhost:5432/fitnexusdb
#      username: user
#      password:
#      driver-class-name: org.postgresql.Driver

  #script-based initialization (to use schema.sql)
  sql:
    init:
      mode: always

    #server:
    #port: 8080
    #error:
    #include-stacktrace: never
springdoc:
  api-docs:
    path: /api-docs