spring:
  application:
    name: fit-nexus

#Add this stuff to run in H2
#  h2:
#    console:
#      enabled: true
  #To specify the name of the database in H2
#  datasource:
#    generate-unique-name: false
#    name: h2database
#Add this stuff to run in H2

#To connect directly to postgresql DB up and running in local machine
#    datasource:
#      name: fitnexusdb
#      url: jdbc:postgresql://localhost:5432/fitnexusdb
#      username: user
#      password:
#      driver-class-name: org.postgresql.Driver

  #script-based initialization (to use schema.sql)
  sql:
    init:
      mode: always

    #server:
    #port: 8080
    #error:
    #include-stacktrace: never
springdoc:
  api-docs:
    path: /api-docs