spring:
  sql: #script-based initialization (to use schema-dev.sql)
    init:
      schema-locations: classpath:schema-dev.sql
      mode: always
#logging:
  #level:
    #org:
      #springframework:
        #security: DEBUG